#' Example K2Taxonomer output
#'
#' An object of class, `K2`, generated by running K2Taxonomer on
#' `data(sample.ExpressionSet)` from `Biobase` R package.
#'
#' @format An object of class `K2`
#' @source data('sample.ExpressionSet', package='Biobase')
"K2res"
